name: DTI_new
channels:
  - pytorch
  - nvidia
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotli-python=1.0.9=py310h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - certifi=2025.8.3=pyhd8ed1ab_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.6.77=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.6=3
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py310h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py310heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - idna=3.7=py310h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.4=py310h06a4308_0
  - jpeg=9e=h5eee18b_3
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=3.0=h295c915_0
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.11.1.6=0
  - libcurand=10.3.7.77=0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.17=h5eee18b_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnpp=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py310h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_1
  - mkl_fft=1.3.10=py310h5eee18b_0
  - mkl_random=1.2.7=py310h1128e8f_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py310h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.2.1=py310h06a4308_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.0.17=h5eee18b_0
  - pillow=10.4.0=py310h5eee18b_0
  - pip=24.2=py310h06a4308_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.15=he870216_1
  - pytorch-cuda=12.1=ha16c6d3_6
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.2=py310h5eee18b_0
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=py310h06a4308_0
  - setuptools=75.1.0=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - sympy=1.13.2=py310h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - typing_extensions=4.11.0=py310h06a4308_0
  - urllib3=2.2.3=py310h06a4308_0
  - wheel=0.44.0=py310h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
    - absl-py==2.1.0
    - accelerate==1.1.1
    - addict==2.4.0
    - aiohappyeyeballs==2.4.3
    - aiohttp==3.10.10
    - aiosignal==1.3.1
    - annotated-types==0.7.0
    - antlr4-python3-runtime==4.9.3
    - anyio==4.8.0
    - appdirs==1.4.4
    - asttokens==2.4.1
    - async-timeout==4.0.3
    - attrs==24.2.0
    - autograd==1.8.0
    - autograd-gamma==0.5.0
    - biopython==1.84
    - cffi==1.17.1
    - cftime==1.6.4.post1
    - click==8.1.7
    - cloudpickle==3.1.0
    - comm==0.2.2
    - contextlib2==21.6.0
    - contourpy==1.3.0
    - cycler==0.12.1
    - cython==3.1.1
    - dataclasses==0.6
    - debugpy==1.8.7
    - decorator==5.1.1
    - deepspeed==0.5.9
    - dgl==2.4.0+cu121
    - dgllife==0.3.2
    - dill==0.3.9
    - distro==1.9.0
    - dllogger==1.0.0
    - dm-tree==0.1.8
    - docker-pycreds==0.4.0
    - easydict==1.13
    - editdistance==0.8.1
    - einops==0.8.0
    - et-xmlfile==2.0.0
    - exceptiongroup==1.2.2
    - executing==2.1.0
    - fair-esm==2.0.0
    - fairseq==0.10.0
    - fonttools==4.54.1
    - formulaic==1.1.1
    - freetype-py==2.5.1
    - frozenlist==1.5.0
    - fsspec==2024.10.0
    - future==1.0.0
    - fvcore==0.1.5.post20221221
    - gensim==4.3.3
    - gitdb==4.0.11
    - gitpython==3.1.43
    - grpcio==1.67.1
    - h11==0.14.0
    - hjson==3.1.0
    - hsluv==5.0.4
    - httpcore==1.0.7
    - httpx==0.28.1
    - huggingface-hub==0.26.2
    - hydra-core==1.3.2
    - hyperopt==0.2.7
    - interface-meta==1.3.0
    - iopath==0.1.10
    - ipykernel==6.29.5
    - ipython==8.29.0
    - jedi==0.19.1
    - jiter==0.8.2
    - joblib==1.4.2
    - jupyter-client==8.6.3
    - jupyter-core==5.7.2
    - kiwisolver==1.4.7
    - lifelines==0.30.0
    - lightning-utilities==0.11.8
    - lmdb==1.5.1
    - lxml==5.4.0
    - markdown==3.7
    - markdown-it-py==3.0.0
    - matplotlib==3.9.2
    - matplotlib-inline==0.1.7
    - mdtraj==1.10.3
    - mdurl==0.1.2
    - ml-collections==0.1.1
    - mol2vec==0.2.2
    - multidict==6.1.0
    - nest-asyncio==1.6.0
    - netcdf4==1.7.2
    - ninja==1.11.1.1
    - numpy==1.26.0
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-ml-py==12.575.51
    - nvidia-nccl-cu12==2.20.5
    - nvidia-nvjitlink-cu12==12.9.86
    - nvidia-nvtx-cu12==12.1.105
    - nvitop==1.5.2
    - omegaconf==2.3.0
    - openai==1.63.2
    - openpyxl==3.1.5
    - packaging==24.1
    - pandarallel==1.6.5
    - pandas==2.2.3
    - parso==0.8.4
    - peewee==3.18.2
    - peft==0.13.2
    - pexpect==4.9.0
    - planarity==0.6
    - platformdirs==4.3.6
    - portalocker==2.10.1
    - prefetch-generator==1.0.3
    - prompt-toolkit==3.0.48
    - propcache==0.2.0
    - propy==1.0.0
    - protobuf==5.28.3
    - psutil==6.1.0
    - ptyprocess==0.7.0
    - pure-eval==0.2.3
    - py-cpuinfo==9.0.0
    - py4j==0.10.9.7
    - pycparser==2.22
    - pydantic==2.9.2
    - pydantic-core==2.23.4
    - pygments==2.18.0
    - pyknotid==0.5.3
    - pyparsing==3.2.0
    - python-dateutil==2.9.0.post0
    - pytorch-lightning==2.4.0
    - pytz==2024.2
    - pyzmq==26.2.0
    - rdkit-pypi==2022.9.5
    - regex==2024.11.6
    - rich==13.9.4
    - sacrebleu==2.5.1
    - safetensors==0.4.5
    - scikit-learn==1.5.2
    - scipy==1.13.1
    - seaborn==0.13.2
    - selfies==2.1.2
    - sentry-sdk==2.19.0
    - setproctitle==1.3.4
    - six==1.16.0
    - smart-open==7.1.0
    - smmap==5.0.1
    - sniffio==1.3.1
    - stack-data==0.6.3
    - tabulate==0.9.0
    - tensorboard==2.18.0
    - tensorboard-data-server==0.7.2
    - tensorboardx==2.6.4
    - termcolor==2.5.0
    - threadpoolctl==3.5.0
    - tokenizers==0.13.3
    - torch==2.4.1
    - torch-cluster==1.6.3+pt24cu124
    - torch-geometric==2.6.1
    - torch-scatter==2.1.2+pt24cu124
    - torch-sparse==0.6.18+pt24cu124
    - torch-spline-conv==1.2.2+pt24cu124
    - torchaudio==2.4.1
    - torchdrug==0.2.1
    - torchmetrics==1.5.1
    - torchvision==0.19.1
    - tornado==6.4.1
    - tqdm==4.66.6
    - traitlets==5.14.3
    - transformers==4.28.0
    - triton==3.0.0
    - tzdata==2024.2
    - unicore==0.0.1
    - vispy==0.15.2
    - wandb==0.18.7
    - wcwidth==0.2.13
    - werkzeug==3.1.3
    - wrapt==1.17.2
    - yacs==0.1.8
    - yarl==1.17.1
prefix: /home/qingyuyang/anaconda3/envs/DTI_new
